domain_path: C:\Users\asus\Desktop\USBToken\USB_CDC_Ultra96v2\usb_mass_storage\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: D:\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
